# Upptime configuration for ferrojulio/upptime

owner: ferrojulio
repo: upptime

# Check every 5 minutes (default). Make it */2 for 2-minute checks.
workflowSchedule: "*/5 * * * *"

# Primary monitors — only public endpoints (Actions run from the public internet)
sites:
  - name: Securite du Sol (root)
    url: https://securite-du-sol.com/
    maxResponseTime: 7000          # Shiny can be slow on cold start; tune later
    expectedStatusCodes: [200, 301, 302]
    maxRedirects: 3
    method: GET
    headers:
      User-Agent: "Upptime (+https://github.com/upptime/upptime)"
      Accept-Language: fr

  - name: Securite du Sol (www)
    url: https://www.securite-du-sol.com/
    expectedStatusCodes: [200, 301, 302]
    maxRedirects: 3

  - name: Farmers app
    url: https://securite-du-sol.com/farmers/
    maxResponseTime: 7000
    expectedStatusCodes: [200, 301, 302]
    maxRedirects: 3

# Status page (served by GitHub Pages for free)
status-website:
  name: "Sécurité du Sol — Status"
  introTitle: "Service Status"
  introMessage: >
    Automated uptime checks for securite-du-sol.com, updated every 5 minutes.
  baseUrl: /upptime               
  theme: night
  favicon: https://securite-du-sol.com/favicon.ico
  logoUrl: https://securite-du-sol.com/Logos.png
  navbar:
    - title: Website
      href: https://securite-du-sol.com/
    - title: GitHub
      href: https://github.com/ferrojulio/upptime



# Localisation / formatting
i18n:
  timezone: Australia/Sydney
  dateFormat: "dd MMM yyyy, HH:mm z"
