# Upptime configuration for ferrojulio/upptime

owner: ferrojulio
repo: upptime

workflowSchedule: "*/5 * * * *"

sites:
  - name: Securite du Sol (root)
    url: https://securite-du-sol.com/
    maxResponseTime: 7000
    expectedStatusCodes: [200, 301, 302]
    maxRedirects: 3
    method: GET
    headers:
      - "User-Agent: Upptime (+https://github.com/upptime/upptime)"
      - "Accept-Language: fr"

  - name: index
    url: https://www.securite-du-sol.com/index/
    expectedStatusCodes: [200, 301, 302]
    maxRedirects: 3

  - name: Farmers app
    url: https://securite-du-sol.com/farmers/
    maxResponseTime: 7000
    expectedStatusCodes: [200, 301, 302]
    maxRedirects: 3

  - name: Policymakers app
    url: https://securite-du-sol.com/policymakers/
    maxResponseTime: 7000
    expectedStatusCodes: [200, 301, 302]
    maxRedirects: 3

status-website:
  name: "Sécurité du Sol — Status"
  introTitle: "Service Status"
  introMessage: >
    Automated uptime checks for securite-du-sol.com, updated every 5 minutes.
  baseUrl: /upptime
  theme: night
  favicon: https://securite-du-sol.com/favicon.ico
  logoUrl: https://securite-du-sol.com/Logos.png
  navbar:
    - title: Website
      href: https://securite-du-sol.com/
    - title: GitHub
      href: https://github.com/ferrojulio/upptime

i18n:
  timezone: Australia/Sydney
  dateFormat: "dd MMM yyyy, HH:mm z"

notifications:
  - type: smtp
    from: "upptime@securite-du-sol.com"   # must be a valid/verified sender with your SMTP provider
    to:   "you@example.com"                # <-- change this to your email
    host: $SMTP_HOST                       # set these as repo Secrets
    port: $SMTP_PORT
    secure: true                           # true for port 465; false for 587 (STARTTLS)
    username: $SMTP_USER
    password: $SMTP_PASS
